[package]
name = "rusty_bustacean"
version = "0.1.0"
authors = ["Slick <jacobfarrell18@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
